language: cpp
matrix:
  include:
    - os: linux
      sudo: required
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
            - cmake
script:
  - mkdir build
  - cd build
  - cmake .. && make
  - ./Tests
